import type { Building, Zone, Road, TruckYard, CargoGate } from './types'

export const cargoBuilding8: Building = {
  id: 'building-8',
  name: 'No.8 Cargo Building',
  nameJa: '第8貨物ビル',
  position: [0, 0, 0],
  size: [200, 15, 180],
  exterior: {
    material: 'corrugated_metal',
    color: '#B0B0B0',
    hasCanopy: true,
    loadingDocks: [
      { id: 'dock-8-1', position: [-80, 0, 92], width: 10, height: 5, hasCanopy: true },
      { id: 'dock-8-2', position: [-60, 0, 92], width: 10, height: 5, hasCanopy: true },
      { id: 'dock-8-3', position: [-40, 0, 92], width: 10, height: 5, hasCanopy: true },
      { id: 'dock-8-4', position: [-20, 0, 92], width: 10, height: 5, hasCanopy: true },
      { id: 'dock-8-5', position: [20, 0, 92], width: 10, height: 5, hasCanopy: true },
      { id: 'dock-8-6', position: [40, 0, 92], width: 10, height: 5, hasCanopy: true },
      { id: 'dock-8-7', position: [60, 0, 92], width: 10, height: 5, hasCanopy: true },
      { id: 'dock-8-8', position: [80, 0, 92], width: 10, height: 5, hasCanopy: true },
      { id: 'dock-8-9', position: [20, 0, -92], width: 10, height: 5, hasCanopy: true },
      { id: 'dock-8-10', position: [50, 0, -92], width: 10, height: 5, hasCanopy: true },
      { id: 'dock-8-11', position: [80, 0, -92], width: 10, height: 5, hasCanopy: true },
      { id: 'dock-8-12', position: [102, 0, -30], width: 10, height: 5, hasCanopy: true },
      { id: 'dock-8-13', position: [102, 0, 30], width: 10, height: 5, hasCanopy: true },
    ],
  },
  interior: {
    zones: [
      {
        id: 'import-area',
        name: 'Import area',
        nameJa: '輸入エリア',
        position: [-50, 0.5, 45],
        size: [95, 0.5, 85],
        color: '#2D7A6B',
        category: 'import',
        floor: 1,
        description: 'Main import processing area - IACT',
        area: 8075,
        handlingCompany: 'IACT',
      },
      {
        id: 'import-counter',
        name: 'Import counter',
        nameJa: '輸入カウンター',
        position: [-30, 0.6, 15],
        size: [28, 0.5, 18],
        color: '#1F6B5C',
        category: 'import',
        floor: 1,
        description: 'Import documentation counter',
        area: 504,
      },
      {
        id: 'automatic-rack',
        name: 'Automatic rack',
        nameJa: '自動ラック',
        position: [-60, 0.6, 35],
        size: [35, 0.5, 35],
        color: '#1F6B5C',
        category: 'import',
        floor: 1,
        description: 'Automated storage rack system',
        area: 1225,
      },
      {
        id: 'agf-area',
        name: 'AGF area',
        nameJa: 'AGFエリア',
        position: [-60, 0.6, 75],
        size: [35, 0.5, 25],
        color: '#1F6B5C',
        category: 'import',
        floor: 1,
        description: 'Automated Guided Forklift area',
        area: 875,
      },
      {
        id: 'export-area',
        name: 'Export area',
        nameJa: '輸出エリア',
        position: [50, 0.5, 0],
        size: [95, 0.5, 175],
        color: '#3B7BBF',
        category: 'export',
        floor: 1,
        description: 'Main export processing area - ANA',
        area: 16625,
      },
      {
        id: 'export-counter',
        name: 'Export counter',
        nameJa: '輸出カウンター',
        position: [25, 0.6, -65],
        size: [30, 0.5, 22],
        color: '#2B6AAE',
        category: 'export',
        floor: 1,
        description: 'Export documentation counter',
        area: 660,
      },
      {
        id: 'valuables-storage',
        name: 'Valuables/animal storage',
        nameJa: '貴重品・動物庫',
        position: [25, 0.6, -40],
        size: [32, 0.5, 24],
        color: '#2B6AAE',
        category: 'special',
        floor: 1,
        description: 'Secure storage for valuables and animals',
        area: 768,
      },
      {
        id: 'temperature-controlled',
        name: 'Temperature-control facility',
        nameJa: '温度管理施設 1,644㎡',
        position: [20, 0.6, -10],
        size: [45, 0.5, 45],
        color: '#6B7B8C',
        category: 'special',
        floor: 1,
        description: 'Temperature controlled storage (1,644㎡)',
        area: 1644,
      },
      {
        id: 'ana-acceptance',
        name: 'ANA flights acceptance area',
        nameJa: 'ANA便 受託エリア',
        position: [70, 0.6, -65],
        size: [50, 0.5, 28],
        color: '#2B6AAE',
        category: 'export',
        floor: 1,
        description: 'ANA flight cargo acceptance area',
        area: 1400,
      },
      {
        id: 'dangerous-goods',
        name: 'Dangerous Goods storage',
        nameJa: '危険物置場',
        position: [65, 0.6, -35],
        size: [38, 0.5, 22],
        color: '#2B6AAE',
        category: 'export',
        floor: 1,
        description: 'Hazardous materials storage',
        area: 836,
      },
      {
        id: 'chs-buildup',
        name: 'CHS 7 build-up areas',
        nameJa: 'CHS 積み付け場 7箇所',
        position: [75, 0.6, 10],
        size: [45, 0.5, 55],
        color: '#2B6AAE',
        category: 'export',
        floor: 1,
        description: 'CHS loading/stowage area (7 locations)',
        area: 2475,
      },
      {
        id: 'agv-area',
        name: 'AGV area',
        nameJa: 'AGVエリア',
        position: [60, 0.6, 55],
        size: [45, 0.5, 40],
        color: '#2B6AAE',
        category: 'export',
        floor: 1,
        description: 'Automated Guided Vehicle area',
        area: 1800,
      },
    ],
    floors: [{ level: 1, height: 15, zones: [] }],
  },
}

export const cargoBuilding7: Building = {
  id: 'building-7',
  name: 'No.7 Cargo Building',
  nameJa: '第7貨物ビル',
  position: [220, 0, -20],
  size: [100, 15, 130],
  exterior: {
    material: 'corrugated_metal',
    color: '#B0B0B0',
    hasCanopy: true,
    loadingDocks: [
      { id: 'dock-7-1', position: [-30, 0, 67], width: 10, height: 5, hasCanopy: true },
      { id: 'dock-7-2', position: [-10, 0, 67], width: 10, height: 5, hasCanopy: true },
      { id: 'dock-7-3', position: [10, 0, 67], width: 10, height: 5, hasCanopy: true },
      { id: 'dock-7-4', position: [30, 0, 67], width: 10, height: 5, hasCanopy: true },
    ],
  },
  interior: {
    zones: [
      {
        id: 'refrigerator',
        name: 'Refrigerator 100㎡',
        nameJa: '冷蔵庫 100㎡',
        position: [-35, 0.5, -45],
        size: [28, 0.5, 35],
        color: '#4A5568',
        category: 'storage',
        floor: 1,
        description: 'Refrigerated storage (100㎡)',
        area: 100,
      },
      {
        id: 'multi-functional',
        name: 'Multi-function area',
        nameJa: '多機能エリア',
        position: [0, 0.5, -45],
        size: [38, 0.5, 35],
        color: '#6B7B8C',
        category: 'storage',
        floor: 1,
        description: 'Multi-functional storage area',
        area: 1330,
      },
      {
        id: 'foreign-carrier',
        name: 'Foreign carrier flights',
        nameJa: '外航便',
        position: [10, 0.5, 20],
        size: [80, 0.5, 80],
        color: '#6B7B8C',
        category: 'storage',
        floor: 1,
        description: 'Foreign carrier flight cargo area',
        area: 6400,
      },
      {
        id: 'chs-building7',
        name: 'CHS',
        nameJa: 'CHS',
        position: [38, 0.6, -45],
        size: [28, 0.5, 28],
        color: '#4A5568',
        category: 'storage',
        floor: 1,
        description: 'CHS area',
        area: 784,
      },
    ],
    floors: [{ level: 1, height: 15, zones: [] }],
  },
}

// 2つの道路のみ（倉庫と被らないように配置）
// Building 8: x=-100〜100, z=-90〜90
// Building 7: x=170〜270, z=-85〜45
// z負の値 = 北（上）、z正の値 = 南（下）
export const roads: Road[] = [
  // 1. 左下から右上への直線道路（倉庫の北側を通る、z < -100）
  { id: 'road-1', path: [[-280, -120], [420, -400]], width: 14, type: 'two_way' },
  
  // 2. 右上から右下への斜めの直線道路（Building 7の右側、x > 300）
  { id: 'road-2', path: [[420, -400], [340, 100]], width: 14, type: 'two_way' },
]

export const truckYards: TruckYard[] = [
  { id: 'truck-yard-8-top', position: [50, 0, -107], size: [90, 0.3, 18], entryPoints: [[50, -125]], exitPoints: [[50, -95]], label: 'Truck yard' },
  { id: 'truck-yard-8-left', position: [-112, 0, 45], size: [18, 0.3, 70], entryPoints: [[-130, 45]], exitPoints: [[-100, 45]], label: 'Truck yard' },
  { id: 'truck-yard-7', position: [220, 0, -107], size: [70, 0.3, 18], entryPoints: [[220, -125]], exitPoints: [[220, -95]], label: 'Truck yard' },
]

export const cargoGate: CargoGate = {
  id: 'northern-gate',
  position: [-200, 0, 100],
  lanes: 4,
  width: 40,
  label: 'Northern cargo gate',
}

export const zoneBoundaries = [
  { id: 'import-export-boundary', points: [[0, 0], [0, 90]], width: 3 },
  { id: 'import-counter-boundary', points: [[-15, 5], [-15, 25], [-45, 25]], width: 2 },
  { id: 'automatic-rack-boundary', points: [[-75, 20], [-75, 55], [-45, 55], [-45, 20]], width: 2 },
  { id: 'agf-boundary', points: [[-75, 60], [-75, 88], [-45, 88]], width: 2 },
  { id: 'export-counter-boundary', points: [[10, -75], [40, -75], [40, -55]], width: 2 },
  { id: 'valuables-boundary', points: [[10, -50], [42, -50], [42, -28]], width: 2 },
  { id: 'temp-control-boundary', points: [[-3, -32], [45, -32], [45, 12], [-3, 12], [-3, -32]], width: 2 },
  { id: 'ana-acceptance-boundary', points: [[45, -78], [95, -78], [95, -52]], width: 2 },
  { id: 'dangerous-boundary', points: [[45, -45], [85, -45], [85, -25]], width: 2 },
  { id: 'chs-boundary', points: [[52, -18], [98, -18], [98, 40], [52, 40], [52, -18]], width: 2 },
  { id: 'agv-boundary', points: [[38, 35], [85, 35], [85, 75]], width: 2 },
]

export const allZones: Zone[] = [
  ...cargoBuilding8.interior.zones,
  ...cargoBuilding7.interior.zones,
]

export const allBuildings: Building[] = [cargoBuilding8, cargoBuilding7]
